import type { InventoryItem, ActiveRecall, UserAlert } from "@/types/database";

export const mockInventory: InventoryItem[] = [
  {
    id: "inv-1",
    user_id: "user-1",
    brand: "Graco",
    product_name: "4Ever DLX 4-in-1 Car Seat",
    model_number: "2074897",
    category: "Baby",
    purchase_date: "2025-11-15",
    source_email_id: "email-001",
    created_at: "2025-11-15T10:00:00Z",
  },
  {
    id: "inv-2",
    user_id: "user-1",
    brand: "Fisher-Price",
    product_name: "Rock 'n Play Sleeper",
    model_number: "FHW27",
    category: "Baby",
    purchase_date: "2025-10-20",
    source_email_id: "email-002",
    created_at: "2025-10-20T10:00:00Z",
  },
  {
    id: "inv-3",
    user_id: "user-1",
    brand: "Similac",
    product_name: "Pro-Advance Infant Formula",
    model_number: null,
    category: "Food",
    purchase_date: "2026-01-05",
    source_email_id: "email-003",
    created_at: "2026-01-05T10:00:00Z",
  },
  {
    id: "inv-4",
    user_id: "user-1",
    brand: "IKEA",
    product_name: "KULLEN 3-Drawer Chest",
    model_number: "803.092.37",
    category: "Home",
    purchase_date: "2026-02-10",
    source_email_id: "email-004",
    created_at: "2026-02-10T10:00:00Z",
  },
  {
    id: "inv-5",
    user_id: "user-1",
    brand: "BabyBjörn",
    product_name: "Baby Carrier Mini",
    model_number: "021056US",
    category: "Baby",
    purchase_date: "2026-01-22",
    source_email_id: "email-005",
    created_at: "2026-01-22T10:00:00Z",
  },
];

export const mockRecalls: ActiveRecall[] = [
  {
    id: "rec-1",
    agency_source: "CPSC",
    agency_id: "CPSC-2025-0234",
    title: "Fisher-Price Rock 'n Play Sleepers Recalled Due to Infant Deaths",
    description:
      "Fisher-Price is recalling about 4.7 million Rock 'n Play Sleepers due to reports of infant fatalities. The sleeper's inclined position poses a suffocation risk.",
    affected_models: ["FHW27", "FHW28", "GDT70", "GNX44"],
    recall_date: "2025-12-01",
    remedy_url: "https://www.cpsc.gov/recalls/fisher-price-rock-n-play",
    embedding: null,
  },
  {
    id: "rec-2",
    agency_source: "FDA",
    agency_id: "FDA-2026-0012",
    title: "Abbott Laboratories Infant Formula Recall - Cronobacter Risk",
    description:
      "Abbott is voluntarily recalling certain Similac, Alimentum, and EleCare powdered infant formulas due to possible Cronobacter sakazakii contamination.",
    affected_models: ["Pro-Advance", "Alimentum", "EleCare"],
    recall_date: "2026-01-15",
    remedy_url: "https://www.fda.gov/safety/recalls/similac-formula",
    embedding: null,
  },
  {
    id: "rec-3",
    agency_source: "CPSC",
    agency_id: "CPSC-2026-0089",
    title: "IKEA KULLEN Dressers Recalled Due to Tip-Over Risk",
    description:
      "IKEA is recalling KULLEN 3- and 5-drawer chests due to serious tip-over and entrapment hazards when not properly anchored to the wall.",
    affected_models: ["803.092.37", "703.092.38", "503.092.39"],
    recall_date: "2026-02-20",
    remedy_url: "https://www.cpsc.gov/recalls/ikea-kullen-dresser",
    embedding: null,
  },
  {
    id: "rec-4",
    agency_source: "NHTSA",
    agency_id: "NHTSA-2026-0045",
    title: "Graco TurboBooster Backless Booster Seats Recalled",
    description:
      "Graco is recalling certain TurboBooster backless booster seats because the seat base may break during use, posing an injury risk to children.",
    affected_models: ["1877966", "1877527", "2002093"],
    recall_date: "2026-03-01",
    remedy_url: "https://www.nhtsa.gov/recalls/graco-turbobooster",
    embedding: null,
  },
  {
    id: "rec-5",
    agency_source: "USDA",
    agency_id: "USDA-2026-0033",
    title: "Tyson Chicken Nuggets Recalled Due to Undeclared Allergen",
    description:
      "Tyson Foods is recalling approximately 30,000 pounds of chicken nuggets that may contain milk, an allergen not declared on the product label.",
    affected_models: ["Fun Nuggets 29oz", "Dino Nuggets 29oz"],
    recall_date: "2026-02-28",
    remedy_url: "https://www.usda.gov/recalls/tyson-chicken-nuggets",
    embedding: null,
  },
];

export const mockAlerts: UserAlert[] = [
  {
    id: "alert-1",
    user_id: "user-1",
    inventory_item_id: "inv-2",
    recall_id: "rec-1",
    match_score: 0.97,
    severity: "high",
    status: "new",
    notified_at: null,
    created_at: "2025-12-02T08:00:00Z",
    inventory_item: mockInventory[1],
    recall: mockRecalls[0],
  },
  {
    id: "alert-2",
    user_id: "user-1",
    inventory_item_id: "inv-3",
    recall_id: "rec-2",
    match_score: 0.82,
    severity: "medium",
    status: "new",
    notified_at: null,
    created_at: "2026-01-16T08:00:00Z",
    inventory_item: mockInventory[2],
    recall: mockRecalls[1],
  },
  {
    id: "alert-3",
    user_id: "user-1",
    inventory_item_id: "inv-4",
    recall_id: "rec-3",
    match_score: 0.95,
    severity: "high",
    status: "confirmed",
    notified_at: "2026-02-21T09:00:00Z",
    created_at: "2026-02-21T08:00:00Z",
    inventory_item: mockInventory[3],
    recall: mockRecalls[2],
  },
];
