import { Resend } from "resend";
import type { UserAlert } from "@/types/database";

let resend: Resend | null = null;

function getResend(): Resend {
  if (!resend) {
    const apiKey = process.env.RESEND_API_KEY;
    if (!apiKey) throw new Error("RESEND_API_KEY is not configured");
    resend = new Resend(apiKey);
  }
  return resend;
}

/**
 * Send a recall alert email notification to the user.
 */
export async function sendRecallAlertEmail(
  userEmail: string,
  alert: UserAlert
): Promise<boolean> {
  try {
    const r = getResend();
    const matchPercent = Math.round(alert.match_score * 100);
    const isHighSeverity = alert.severity === "high";

    const { error } = await r.emails.send({
      from: "SafeGuard Inbox <alerts@safeguard.io>",
      to: userEmail,
      subject: `${isHighSeverity ? "⚠️ HIGH ALERT" : "⚡ Recall Notice"}: ${alert.recall?.title || "Product Recall Detected"}`,
      html: `
        <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 600px; margin: 0 auto;">
          <div style="background: ${isHighSeverity ? "#ef4444" : "#f59e0b"}; color: white; padding: 20px; border-radius: 8px 8px 0 0;">
            <h1 style="margin: 0; font-size: 20px;">
              ${isHighSeverity ? "⚠️ High-Confidence Recall Match" : "⚡ Possible Recall Match"}
            </h1>
            <p style="margin: 8px 0 0; opacity: 0.9; font-size: 14px;">
              ${matchPercent}% match confidence
            </p>
          </div>
          
          <div style="border: 1px solid #e2e8f0; border-top: none; padding: 24px; border-radius: 0 0 8px 8px;">
            <h2 style="margin: 0 0 8px; font-size: 16px; color: #0f172a;">Your Product</h2>
            <div style="background: #f8fafc; padding: 12px; border-radius: 6px; margin-bottom: 16px;">
              <p style="margin: 0; font-weight: 600;">
                ${alert.inventory_item?.brand || ""} ${alert.inventory_item?.product_name || ""}
              </p>
              ${alert.inventory_item?.model_number ? `<p style="margin: 4px 0 0; color: #64748b; font-size: 14px;">Model: ${alert.inventory_item.model_number}</p>` : ""}
            </div>
            
            <h2 style="margin: 0 0 8px; font-size: 16px; color: #0f172a;">Recall Notice</h2>
            <p style="margin: 0 0 4px; font-weight: 600;">${alert.recall?.title || ""}</p>
            <p style="margin: 0 0 16px; color: #64748b; font-size: 14px;">
              ${alert.recall?.description || ""}
            </p>
            
            ${alert.recall?.remedy_url ? `
            <a href="${alert.recall.remedy_url}" style="display: inline-block; background: #2563eb; color: white; padding: 10px 20px; border-radius: 6px; text-decoration: none; font-weight: 500; font-size: 14px;">
              View Recall Details →
            </a>
            ` : ""}
            
            <hr style="border: none; border-top: 1px solid #e2e8f0; margin: 24px 0;" />
            
            <p style="margin: 0; color: #94a3b8; font-size: 12px;">
              This alert was generated by SafeGuard Inbox. 
              <a href="${process.env.NEXT_PUBLIC_APP_URL}/dashboard" style="color: #2563eb;">
                View your dashboard
              </a>
            </p>
          </div>
        </div>
      `,
    });

    if (error) {
      console.error("Failed to send alert email:", error);
      return false;
    }

    return true;
  } catch (error) {
    console.error("Email notification error:", error);
    return false;
  }
}
